name: Supabase Keep Alive

on:
  workflow_dispatch: # 手動
  schedule: # 每日 05:00 UTC
    - cron: "0 5 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    environment: production # 如無環境層 secrets，可移除

    env:
      SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # 加快安裝

      # ① 安裝專案依賴（含 typescript、supabase-js…）
      - name: Install dependencies
        run: npm ci --ignore-scripts

      # ② 依照 tsconfig 編譯（tsconfig.json 已含 "skipLibCheck": true）
      - name: Build keep-alive
        run: npx tsc -p tsconfig.json --outDir dist

      # ③ 執行產生的 JS
      - name: Run keep-alive
        run: node dist/src/keepAlive.js
